# Generated by Django 3.2.5 on 2021-08-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
